/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#fcdeb5",
        "on-secondary": "#ffffff",
        "surface-container": "var(--bg-surface-container)",
        "on-tertiary-fixed-variant": "#574425",
        "on-primary-fixed": "var(--text-on-surface)",
        "outline": "#76777d",
        "surface-container-highest": "var(--bg-surface-container-high)",
        "tertiary": "#000000",
        "secondary-fixed": "#d5e3fc",
        "surface-tint": "var(--text-primary)",
        "on-secondary-container": "var(--text-on-primary-container)",
        "inverse-primary": "#bec6e0",
        "on-background": "var(--text-on-surface)",
        "secondary-fixed-dim": "#b9c7df",
        "background": "var(--bg-background)",
        "tertiary-fixed-dim": "#dec29a",
        "outline-variant": "var(--border-outline-variant)",
        "primary": "var(--text-primary)",
        "primary-container": "var(--bg-primary-container)",
        "on-secondary-fixed": "#0d1c2e",
        "on-surface-variant": "var(--text-on-surface-variant)",
        "on-surface": "var(--text-on-surface)",
        "surface-container-lowest": "var(--bg-surface-container-lowest)",
        "on-primary-container": "var(--text-on-primary-container)",
        "secondary-container": "var(--bg-surface-container-low)",
        "primary-fixed": "#dae2fd",
        "inverse-on-surface": "#f3f0f2",
        "on-error-container": "#93000a",
        "surface-dim": "var(--bg-surface-container-low)",
        "surface-container-high": "var(--bg-surface-container-high)",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#3a485b",
        "surface-variant": "var(--bg-surface-variant)",
        "tertiary-container": "#271901",
        "on-tertiary-container": "#98805d",
        "error-container": "#ffdad6",
        "surface-container-low": "var(--bg-surface-container-low)",
        "surface": "var(--bg-surface)",
        "on-error": "#ffffff",
        "secondary": "var(--text-secondary)",
        "on-tertiary-fixed": "#271901",
        "surface-bright": "var(--bg-surface)",
        "inverse-surface": "#303032",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed-variant": "#3f465c",
        "on-primary": "var(--text-on-primary)",
        "error": "#ba1a1a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "sm": "12px",
        "lg": "48px",
        "md": "24px",
        "container-max": "1280px",
        "xs": "4px",
        "xl": "80px",
        "base": "8px",
        "gutter": "24px"
      },
      fontFamily: {
        "display-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg-mobile": ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["30px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
