/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#fcdeb5",
        "on-secondary": "#ffffff",
        "surface-container": "#f0edef",
        "on-tertiary-fixed-variant": "#574425",
        "on-primary-fixed": "#131b2e",
        "outline": "#76777d",
        "surface-container-highest": "#e4e2e4",
        "tertiary": "#000000",
        "secondary-fixed": "#d5e3fc",
        "surface-tint": "#565e74",
        "on-secondary-container": "#57657a",
        "inverse-primary": "#bec6e0",
        "on-background": "#1b1b1d",
        "secondary-fixed-dim": "#b9c7df",
        "background": "#fcf8fa",
        "tertiary-fixed-dim": "#dec29a",
        "outline-variant": "#c6c6cd",
        "primary": "#000000",
        "primary-container": "#131b2e",
        "on-secondary-fixed": "#0d1c2e",
        "on-surface-variant": "#45464d",
        "on-surface": "#1b1b1d",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#7c839b",
        "secondary-container": "#d5e3fc",
        "primary-fixed": "#dae2fd",
        "inverse-on-surface": "#f3f0f2",
        "on-error-container": "#93000a",
        "surface-dim": "#dcd9db",
        "surface-container-high": "#eae7e9",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#3a485b",
        "surface-variant": "#e4e2e4",
        "tertiary-container": "#271901",
        "on-tertiary-container": "#98805d",
        "error-container": "#ffdad6",
        "surface-container-low": "#f6f3f5",
        "surface": "#fcf8fa",
        "on-error": "#ffffff",
        "secondary": "#515f74",
        "on-tertiary-fixed": "#271901",
        "surface-bright": "#fcf8fa",
        "inverse-surface": "#303032",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed-variant": "#3f465c",
        "on-primary": "#ffffff",
        "error": "#ba1a1a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "sm": "12px",
        "lg": "48px",
        "md": "24px",
        "container-max": "1280px",
        "xs": "4px",
        "xl": "80px",
        "base": "8px",
        "gutter": "24px"
      },
      fontFamily: {
        "display-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"]
      },
      fontSize: {
        "display-lg-mobile": ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["30px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
